Update Build.yml

diff --git a/.github/workflows/Build.yml b/.github/workflows/Build.yml
--- a/.github/workflows/Build.yml
+++ b/.github/workflows/Build.yml
@@ -1,337 +1,191 @@
 name: Build
+permissions: write-all
 on:
+  workflow_dispatch:
+    inputs:
+      version:
+        description: "Tag version to release"
+        required: false
   push:
+    branches:
+      - master
     tags:
       - v*
     paths-ignore:
       - 'README.md'
       - '.github/ISSUE_TEMPLATE/**'
       - '.github/workflows/issues.yml'
-  workflow_dispatch:
-
-permissions: write-all
 
 jobs:
-  windows:
+  build:
     strategy:
       fail-fast: false
       matrix:
-        arch:
-          - x64
-          - ia32
-          - arm64
-    runs-on: windows-latest
+        include:
+          # Windows
+          - os: windows-latest
+            arch: x64
+          - os: windows-latest
+            arch: ia32
+          - os: windows-latest
+            arch: arm64
+          # Windows 7
+          - os: windows-latest
+            arch: x64
+            win7: true
+          - os: windows-latest
+            arch: ia32
+            win7: true
+          # Linux
+          - os: ubuntu-latest
+            arch: x64
+          - os: ubuntu-latest
+            arch: arm64
+          # macOS
+          - os: macos-latest
+            arch: x64
+          - os: macos-latest
+            arch: arm64
+          # macOS 10
+          - os: macos-latest
+            arch: x64
+            catalina: true
+          - os: macos-latest
+            arch: arm64
+            catalina: true
+    runs-on: ${{ matrix.os }}
     steps:
       - name: Checkout
         uses: actions/checkout@v4
-      - name: Check out Mihomo Party
-        uses: actions/checkout@v3
-        with:
-          repository: mihomo-party-org/mihomo-party
-          ref: fa3c4121460ebf4ca4412a38b29a7f3f07075c9b
-          path: mihomo-party
-      - name: Customize
-        shell: bash
-        run: |
-          cp ../customize.sh ./
-          chmod +x customize.sh
-          ./customize.sh
-        working-directory: mihomo-party
-      - name: Setup pnpm
-        run: npm install -g pnpm
-      - name: Install Dependencies
-        env:
-          npm_config_arch: ${{ matrix.arch }}
-          npm_config_target_arch: ${{ matrix.arch }}
-        run: |
-          pnpm install
-          pnpm add @mihomo-party/sysproxy-win32-${{ matrix.arch }}-msvc
-          pnpm prepare --${{ matrix.arch }}
-      - name: Build
-        env:
-          npm_config_arch: ${{ matrix.arch }}
-          npm_config_target_arch: ${{ matrix.arch }}
-        run: pnpm build:win --${{ matrix.arch }}
-      - name: Add Portable Flag
-        run: |
-          New-Item -Path "PORTABLE" -ItemType File
-          Get-ChildItem dist/*portable.7z | ForEach-Object {
-            7z a $_.FullName PORTABLE
-          }
-      - name: Generate checksums
-        run: pnpm checksum setup.exe portable.7z
-      - name: Upload Artifacts
-        if: startsWith(github.ref, 'refs/heads/')
-        uses: actions/upload-artifact@v4
-        with:
-          name: Windows ${{ matrix.arch }}
-          path: |
-            dist/*.sha256
-            dist/*setup.exe
-            dist/*portable.7z
-          if-no-files-found: error
-      - name: Publish Release
-        if: startsWith(github.ref, 'refs/tags/v')
-        uses: softprops/action-gh-release@v2
-        with:
-          files: |
-            dist/*.sha256
-            dist/*setup.exe
-            dist/*portable.7z
-          body_path: changelog.md
-          token: ${{ secrets.GITHUB_TOKEN }}
 
-  windows7:
-    strategy:
-      fail-fast: false
-      matrix:
-        arch:
-          - x64
-          - ia32
-    runs-on: windows-latest
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v4
       - name: Check out Mihomo Party
         uses: actions/checkout@v3
         with:
           repository: mihomo-party-org/mihomo-party
           ref: fa3c4121460ebf4ca4412a38b29a7f3f07075c9b
           path: mihomo-party
-      - name: Customize
+
+      - name: Customize Mihomo Party
         shell: bash
+        working-directory: mihomo-party
         run: |
           cp ../customize.sh ./
           chmod +x customize.sh
           ./customize.sh
-        working-directory: mihomo-party
+
       - name: Setup pnpm
-        run: npm install -g pnpm
-      - name: Install Dependencies
+        uses: pnpm/action-setup@v2
+        with:
+          version: 8
+
+      - name: Install Dependencies and Prepare
+        working-directory: mihomo-party
         env:
           npm_config_arch: ${{ matrix.arch }}
           npm_config_target_arch: ${{ matrix.arch }}
         run: |
           pnpm install
-          pnpm add @mihomo-party/sysproxy-win32-${{ matrix.arch }}-msvc
-          pnpm add -D electron@22.3.27
-          (Get-Content electron-builder.yml) -replace 'windows', 'win7' | Set-Content electron-builder.yml
+          pnpm add @mihomo-party/sysproxy-${{ matrix.os == 'windows-latest' && 'win32' || matrix.os == 'ubuntu-latest' && 'linux' || 'darwin' }}-${{ matrix.arch }}${{ matrix.os == 'ubuntu-latest' && '-gnu' || matrix.os == 'windows-latest' && '-msvc' || '' }}
+          ${{ matrix.win7 && 'pnpm add -D electron@22.3.27' || matrix.catalina && 'pnpm add -D electron@32.2.2' || '' }}
+          ${{ matrix.win7 && '(Get-Content electron-builder.yml) -replace ''windows'', ''win7'' | Set-Content electron-builder.yml' || matrix.catalina && 'sed -i "" -e "s/macos/catalina/" electron-builder.yml' || matrix.os == 'ubuntu-latest' && 'sed -i "s/productName: Mihomo Party/productName: mihomo-party/" electron-builder.yml' || '' }}
           pnpm prepare --${{ matrix.arch }}
+
       - name: Build
+        working-directory: mihomo-party
         env:
           npm_config_arch: ${{ matrix.arch }}
           npm_config_target_arch: ${{ matrix.arch }}
-        run: pnpm build:win --${{ matrix.arch }}
+        run: |
+          ${{ contains(matrix.os, 'macos') && 'chmod +x build/pkg-scripts/postinstall' || '' }}
+          pnpm build:${{ matrix.os == 'windows-latest' && 'win' || matrix.os == 'ubuntu-latest' && 'linux' || 'mac' }} --${{ matrix.arch }}
+
       - name: Add Portable Flag
+        if: matrix.os == 'windows-latest'
+        working-directory: mihomo-party
+        shell: pwsh
         run: |
           New-Item -Path "PORTABLE" -ItemType File
           Get-ChildItem dist/*portable.7z | ForEach-Object {
             7z a $_.FullName PORTABLE
           }
+
       - name: Generate checksums
-        run: pnpm checksum setup.exe portable.7z
+        working-directory: mihomo-party
+        run: pnpm checksum ${{ matrix.os == 'windows-latest' && 'setup.exe portable.7z' || matrix.os == 'ubuntu-latest' && '.deb .rpm' || '.pkg' }}
+
       - name: Upload Artifacts
-        if: startsWith(github.ref, 'refs/heads/')
         uses: actions/upload-artifact@v4
         with:
-          name: Win7 ${{ matrix.arch }}
+          name: ${{ matrix.win7 && 'Win7' || matrix.catalina && 'Catalina' || matrix.os == 'windows-latest' && 'Windows' || matrix.os == 'ubuntu-latest' && 'Linux' || 'MacOS' }} ${{ matrix.arch }}
           path: |
-            dist/*.sha256
-            dist/*setup.exe
-            dist/*portable.7z
+            mihomo-party/dist/*.sha256
+            ${{ matrix.os == 'windows-latest' && 'mihomo-party/dist/*setup.exe mihomo-party/dist/*portable.7z' || matrix.os == 'ubuntu-latest' && 'mihomo-party/dist/*.deb mihomo-party/dist/*.rpm' || 'mihomo-party/dist/*.pkg' }}
           if-no-files-found: error
-      - name: Publish Release
-        if: startsWith(github.ref, 'refs/tags/v')
-        uses: softprops/action-gh-release@v2
-        with:
-          files: |
-            dist/*.sha256
-            dist/*setup.exe
-            dist/*portable.7z
-          body_path: changelog.md
-          token: ${{ secrets.GITHUB_TOKEN }}
-  linux:
-    strategy:
-      fail-fast: false
-      matrix:
-        arch:
-          - x64
-          - arm64
+
+  pre-release:
+    needs: [build]
     runs-on: ubuntu-latest
     steps:
       - name: Checkout
         uses: actions/checkout@v4
-      - name: Check out Mihomo Party
-        uses: actions/checkout@v3
+
+      - name: Download Artifacts
+        uses: actions/download-artifact@v4
         with:
-          repository: mihomo-party-org/mihomo-party
-          ref: fa3c4121460ebf4ca4412a38b29a7f3f07075c9b
-          path: mihomo-party
-      - name: Customize
-        run: |
-          cp ../customize.sh ./
-          chmod +x customize.sh
-          ./customize.sh
-        working-directory: mihomo-party
-      - name: Setup pnpm
-        run: npm install -g pnpm
-      - name: Install Dependencies
+          path: bin/
+          merge-multiple: true
+
+      - name: Delete Pre-release
         env:
-          npm_config_arch: ${{ matrix.arch }}
-          npm_config_target_arch: ${{ matrix.arch }}
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         run: |
-          pnpm install
-          pnpm add @mihomo-party/sysproxy-linux-${{ matrix.arch }}-gnu
-          sed -i "s/productName: Mihomo Party/productName: mihomo-party/" electron-builder.yml
-          pnpm prepare --${{ matrix.arch }}
-      - name: Build
-        env:
-          npm_config_arch: ${{ matrix.arch }}
-          npm_config_target_arch: ${{ matrix.arch }}
-        run: pnpm build:linux --${{ matrix.arch }}
-      - name: Generate checksums
-        run: pnpm checksum .deb .rpm
-      - name: Upload Artifacts
-        if: startsWith(github.ref, 'refs/heads/')
-        uses: actions/upload-artifact@v4
-        with:
-          name: Linux ${{ matrix.arch }}
-          path: |
-            dist/*.sha256
-            dist/*.deb
-            dist/*.rpm
-          if-no-files-found: error
-      - name: Publish Release
-        if: startsWith(github.ref, 'refs/tags/v')
+          if ! gh release delete pre-release --yes; then
+            echo "Failed to delete release, but continuing..."
+          fi
+          git log -1 --pretty=format:"%s%n%b" > changelog.md
+
+      - name: Publish Prerelease
+        if: success()
         uses: softprops/action-gh-release@v2
         with:
-          files: |
-            dist/*.sha256
-            dist/*.deb
-            dist/*.rpm
+          tag_name: pre-release
           body_path: changelog.md
-          token: ${{ secrets.GITHUB_TOKEN }}
+          files: |
+            bin/dist/*
+          prerelease: true
 
-  macos:
-    strategy:
-      fail-fast: false
-      matrix:
-        arch:
-          - x64
-          - arm64
-    runs-on: macos-latest
+  release:
+    if: startsWith(github.ref, 'refs/tags/v') || (github.event_name == 'workflow_dispatch' && github.event.inputs.version != '')
+    needs: [build]
+    runs-on: ubuntu-latest
     steps:
       - name: Checkout
         uses: actions/checkout@v4
-      - name: Check out Mihomo Party
-        uses: actions/checkout@v3
         with:
-          repository: mihomo-party-org/mihomo-party
-          ref: fa3c4121460ebf4ca4412a38b29a7f3f07075c9b
-          path: mihomo-party
-      - name: Customize
-        run: |
-          cp ../customize.sh ./
-          chmod +x customize.sh
-          ./customize.sh
-        working-directory: mihomo-party
-      - name: Setup pnpm
-        run: npm install -g pnpm
-      - name: Install Dependencies
-        env:
-          npm_config_arch: ${{ matrix.arch }}
-          npm_config_target_arch: ${{ matrix.arch }}
-        run: |
-          pnpm install
-          pnpm add @mihomo-party/sysproxy-darwin-${{ matrix.arch }}
-          pnpm prepare --${{ matrix.arch }}
-      - name: Build
-        env:
-          npm_config_arch: ${{ matrix.arch }}
-          npm_config_target_arch: ${{ matrix.arch }}
-        run: |
-          chmod +x build/pkg-scripts/postinstall
-          pnpm build:mac --${{ matrix.arch }}
-      - name: Generate checksums
-        run: pnpm checksum .pkg
-      - name: Upload Artifacts
-        if: startsWith(github.ref, 'refs/heads/')
-        uses: actions/upload-artifact@v4
-        with:
-          name: MacOS ${{ matrix.arch }}
-          path: |
-            dist/*.sha256
-            dist/*.pkg
-          if-no-files-found: error
-      - name: Publish Release
-        if: startsWith(github.ref, 'refs/tags/v')
-        uses: softprops/action-gh-release@v2
-        with:
-          files: |
-            dist/*.sha256
-            dist/*.pkg
-          body_path: changelog.md
-          token: ${{ secrets.GITHUB_TOKEN }}
+          fetch-depth: '0'
+          fetch-tags: 'true'
 
-  macos10:
-    strategy:
-      fail-fast: false
-      matrix:
-        arch:
-          - x64
-          - arm64
-    runs-on: macos-latest
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v4
-      - name: Check out Mihomo Party
-        uses: actions/checkout@v3
-        with:
-          repository: mihomo-party-org/mihomo-party
-          ref: fa3c4121460ebf4ca4412a38b29a7f3f07075c9b
-          path: mihomo-party
-      - name: Customize
-        run: |
-          cp ../customize.sh ./
-          chmod +x customize.sh
-          ./customize.sh
-        working-directory: mihomo-party
       - name: Setup pnpm
-        run: npm install -g pnpm
-      - name: Install Dependencies
-        env:
-          npm_config_arch: ${{ matrix.arch }}
-          npm_config_target_arch: ${{ matrix.arch }}
-        run: |
-          pnpm install
-          pnpm add @mihomo-party/sysproxy-darwin-${{ matrix.arch }}
-          pnpm add -D electron@32.2.2
-          pnpm prepare --${{ matrix.arch }}
-      - name: Build
-        env:
-          npm_config_arch: ${{ matrix.arch }}
-          npm_config_target_arch: ${{ matrix.arch }}
-        run: |
-          sed -i "" -e "s/macos/catalina/" electron-builder.yml
-          chmod +x build/pkg-scripts/postinstall
-          pnpm build:mac --${{ matrix.arch }}
-      - name: Generate checksums
-        run: pnpm checksum .pkg
-      - name: Upload Artifacts
-        if: startsWith(github.ref, 'refs/heads/')
-        uses: actions/upload-artifact@v4
+        uses: pnpm/action-setup@v2
         with:
-          name: Catalina ${{ matrix.arch }}
-          path: |
-            dist/*.sha256
-            dist/*.pkg
-          if-no-files-found: error
+          version: 8
+
+      - uses: actions/download-artifact@v4
+        with:
+          path: bin/
+          merge-multiple: true
+
+      - name: Delete Current
+        uses: 8Mi-Tech/delete-release-assets-action@main
+        with:
+          github_token: ${{ secrets.GITHUB_TOKEN }}
+          tag: ${{ github.event.inputs.version != '' && github.event.inputs.version || github.ref }}
+          deleteOnlyFromDrafts: false
+
       - name: Publish Release
-        if: startsWith(github.ref, 'refs/tags/v')
+        if: success()
         uses: softprops/action-gh-release@v2
         with:
+          tag_name: ${{ github.event.inputs.version != '' && github.event.inputs.version || github.ref }}
           files: |
-            dist/*.sha256
-            dist/*.pkg
-          body_path: changelog.md
-          token: ${{ secrets.GITHUB_TOKEN }}
+            bin/dist/*
